theme: minima
title: SymptoWiz
description: SymptoWiz adalah aplikasi prediksi penyakit berdasarkan input gejala pasien, dilengkapi dengan saran obat dan pengobatan, serta saran dokter terbaik untuk perawatan.
